# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
backend:
  name: backend
  namespace: app-backend
  image: artifactory.mrgreen.tech/docker/mrg/demos/k8s-test-app/backend
  tag: latest
  pullPolicy: Always

  replicaCount: 1

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 3002

# Database service endpoint. Should match the database chart.
mongo:
  namespace: app-database
  service:
    port: 27017
