apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sudo
  namespace: red
rules:
- apiGroups:
  - policy
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
