# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

---
frontend:
  name: frontend
  namespace: app-frontend
  image: artifactory.mrgreen.tech/docker/mrg/demos/k8s-test-app/frontend
  tag: latest
  pullPolicy: Always

  replicaCount: 1

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: NodePort
    port: 31080

backend:
  namespace: app-backend
