kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# Disable kindnet to use cilium instead
networking:
  disableDefaultCNI: true
# kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.6/install/kubernetes/quick-install.yaml
