apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: blue-egress
  namespace: blue
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            color: red
      # Allow egress to kube-dns for nameresolution
      - namespaceSelector:
          matchLabels:
            system: "true"
        podSelector:
            matchLabels:
              k8s-app: kube-dns
