apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: red
  namespace: red
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - patch
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - patch
  - update
  - delete
