apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blue
  namespace: blue
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: blue
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: blue
