apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-root
  name: demo-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-root
  template:
    metadata:
      labels:
        app: demo-root
    spec:
      # You can specify the security context explicitly
      securityContext:
        runAsUser: 0
      containers:
      # This image runs as root
      - image: nginx
        name: nginx
        ports:
          - name: http
            containerPort: 80
