apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sudoer
  namespace: red
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sudo
subjects:
- kind: ServiceAccount
  name: default
  namespace: red
# Check with
# kubectl -n red auth can-i use podsecuritypolicy/permissive --as system:serviceaccount:red:default
