apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sudo
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - permissive
  resources:
  - podsecuritypolicies
  verbs:
  - use
