apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  #name: sample-frontend
  namespace: {{ .Values.frontend.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: "frontend"
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: frontend
      targetPort: 3000
      {{ if (eq .Values.frontend.service.type "NodePort") }}
      nodePort: {{ .Values.frontend.service.port }}
      {{ end }}
      port: {{ .Values.frontend.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: "frontend"
