apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged
        name: nginx
        ports:
          - name: http
            containerPort: 8080
      # This image runs as root
      # - image: nginx
      #   name: nginx
      #   ports:
      #     - name: http
      #       containerPort: 80
